### ISSUE TITLE
Embedding of Relations

### ISSUE THREAD

**Issue by snash4** [yangji9181/HNE#2]
Hi, 
 I ran your code for DistMult on PubMed dataset. 
It saves embeddings of entities, where does it save the embedding of relations. 
I want to use them in scoring function and calculate MRR and Hits. 
Thanks.

**Comment by yangji9181** [comment]
Hi,
We did not save the embedding of relations because for HIN embeddings by default we only care about the entity (node) embeddings. If you want to get the relation embeddings you will need to fork and modify our code, or refer to the original DisMult code we have used (https://github.com/TimDettmers/ConvE). 

Thanks!

**Comment by snash4** [comment]
Thanks for the reply and pointer towards the code.
 ps:
It would be great if you could add code to calculate MRR and Hits (filtered and raw)
Your repo code is clean and easy to follow.

**Comment by yangji9181** [comment]
Thanks! We will consider it. It is our goal to make the repo easy to use :)
