### ISSUE TITLE
About config.dat in HAN

### ISSUE THREAD

**Issue by zxp0903** [yangji9181/HNE#6]
I am confused about what to put in _config.dat_ of model HAN, you said **config.dat: The first line specifies the targeting node type. The second line specifies the targeting link type. The third line specifies the information related to each link type, e.g., {head_node_type}\t{tail_node_type}\t{link_type}.** I don't understand it fully.

**Comment by xiaoyuxin1002** [comment]
Hi, sorry about the confusion.
For example, say you want to produce the embedding of nodes with Node_Type_ID = 0 (since HAN can only produce the embedding of 1 node type at a time), and the unsupervised training of HAN is based on the links with Link_Type_ID = 1 (the unsupervised training requires links between nodes of the targeting node type, that is, links with Link_Type_ID = 1 are between nodes with Node_Type_ID = 0). Then you should put "0" in the first line of config.dat and "1" in the second line.
The third line specifies the types of nodes on both sides of a link type. For example, if links with Link_Type_ID = 1 connect nodes with Node_Type_ID = 0 to nodes with Node_Type_ID = 0, then you should write "0,0,1" as one entry. Then you do so for each link type and the entries are separated by "\t".

**Comment by HQ-LV** [comment]
Hello, I have a question about config file of HAN.

You said :
> For example, if links with Link_Type_ID = 1 connect nodes with Node_Type_ID = 0 to nodes with Node_Type_ID = 0, then you should write "0,0,1" as one entry. 

I am wondering if the targeting link type in the second line can only be the link that connects two same node type (which is the targeting node type in the first line)?
