### ISSUE TITLE
About source of HAN

### ISSUE THREAD

**Issue by null-id** [yangji9181/HNE#8]
Hi, I am curious about why do you refer the source code of HAN as NLAH? Is the model in HAN folder HAN model?

https://github.com/yangji9181/HNE/tree/master/Model/HAN

**Comment by xiaoyuxin1002** [comment]
Yes, the model in HAN folder is indeed the HAN model. 
NLAH is another model very similar to HAN in the sense that NLAH considers extra non-local features in addition to the local features considered in HAN.
We referred to NLAH implementation in the HAN model because the NLAH implementation supports sampling-based mini-batch training and therefore, we adopted and modified the NLAH implementation for HAN in our HNE project.
